### ISSUE TITLE
Empty controlled_dataset.yml error

### ISSUE THREAD

**Issue by AlesCUMSI** [EGA-archive/beacon2-ri-api#376]
Hi,
docker container beacon-permissions is throwing out this error in log when I clear/empty file "controlled_datasets.yml".
Here is the output:
2024-09-19 15:28:02 Traceback (most recent call last):
2024-09-19 15:28:02   File "/beacon/permissions/plugins.py", line 74, in get
2024-09-19 15:28:02     for cdataset in self.db.get(username):
2024-09-19 15:28:02 AttributeError: 'NoneType' object has no attribute 'get'
2024-09-19 15:28:02 
2024-09-19 15:28:02 During handling of the above exception, another exception occurred:
2024-09-19 15:28:02 
2024-09-19 15:28:02 Traceback (most recent call last):
2024-09-19 15:28:02   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
2024-09-19 15:28:02     resp = await request_handler(request)
2024-09-19 15:28:02   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
2024-09-19 15:28:02     resp = await handler(request)
2024-09-19 15:28:02   File "/beacon/permissions/auth.py", line 180, in decorated
2024-09-19 15:28:02     return await func(request, username, list_visa_datasets)
2024-09-19 15:28:02   File "/beacon/permissions/__main__.py", line 44, in permission
2024-09-19 15:28:02     datasets = await request.app['permissions'].get(username, requested_datasets=requested_datasets)
2024-09-19 15:28:02   File "/beacon/permissions/plugins.py", line 81, in get
2024-09-19 15:28:02     permissions_dict[username]=[]
2024-09-19 15:28:02 TypeError: 'NoneType' object does not support item assignment

I think there might be bugs in function get in file permissions/plugins.py:
- self.db is None if file is empty
- also self.db.get also return None

**Comment by costero-e** [comment]
Hi @AlesCUMSI,

I don't know if this is not allowing you to use some kind of own implementation but this is expected behaviour, as controlled_datasets can't be empty at all (at least it needs the first line) as it serves as a dictionary through which the permissions look to get the relationship between users and permissions.

Let me know if you have any kind of suggestion related to this.

Best,

Oriol
